//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIRESEP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoEstudios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InfoEstudios()
        {
            this.infoEstudios_perfilProfesional = new HashSet<infoEstudios_perfilProfesional>();
        }
    
        public int idEstudios { get; set; }
        public Nullable<int> idGradoEstudio { get; set; }
        public Nullable<int> idInstitucion { get; set; }
        public Nullable<int> idCarrera { get; set; }
    
        public virtual Carrera Carrera { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<infoEstudios_perfilProfesional> infoEstudios_perfilProfesional { get; set; }
        public virtual InfoGradoEstudio InfoGradoEstudio { get; set; }
        public virtual InfoInstitucion InfoInstitucion { get; set; }
    }
}
