//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIRESEP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoLaboral
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InfoLaboral()
        {
            this.infoLaboral_perfilProfesional = new HashSet<infoLaboral_perfilProfesional>();
        }
    
        public int idInfoLaboral { get; set; }
        public string profesion { get; set; }
        public Nullable<int> tiempoExperiencia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<infoLaboral_perfilProfesional> infoLaboral_perfilProfesional { get; set; }
    }
}
