//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIRESEP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class infoLaboral_perfilProfesional
    {
        public int idInfoLaboralProfesional { get; set; }
        public Nullable<int> idInfoLaboral { get; set; }
        public Nullable<int> idPerfilProfesional { get; set; }
    
        public virtual InfoLaboral InfoLaboral { get; set; }
        public virtual PerfilPersona PerfilPersona { get; set; }
    }
}
