//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIRESEP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoRequisitos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InfoRequisitos()
        {
            this.PerfilDelConcurso = new HashSet<PerfilDelConcurso>();
        }
    
        public int idInfoRequisitos { get; set; }
        public Nullable<int> idIdioma { get; set; }
        public Nullable<int> idGradoEstudio { get; set; }
        public Nullable<int> idHabilidad { get; set; }
        public Nullable<int> idCarrera { get; set; }
    
        public virtual Carrera Carrera { get; set; }
        public virtual InfoGradoEstudio InfoGradoEstudio { get; set; }
        public virtual InfoHabilidad InfoHabilidad { get; set; }
        public virtual InfoIdioma InfoIdioma { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PerfilDelConcurso> PerfilDelConcurso { get; set; }
    }
}
