//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIRESEP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class perfilProfesional_PerfilConcurso
    {
        public int idMatch { get; set; }
        public Nullable<int> idConcurso { get; set; }
        public Nullable<int> idPerfilProfesional { get; set; }
        public Nullable<decimal> porcentajeMatch { get; set; }
        public string usuarioCrea { get; set; }
        public Nullable<System.DateTime> fechaCreacion { get; set; }
        public string usuarioModifica { get; set; }
        public Nullable<System.DateTime> fechaModifica { get; set; }
    
        public virtual PerfilDelConcurso PerfilDelConcurso { get; set; }
        public virtual PerfilPersona PerfilPersona { get; set; }
    }
}
