//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIRESEP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PerfilDelConcurso
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PerfilDelConcurso()
        {
            this.aplicaciones = new HashSet<aplicaciones>();
            this.perfilProfesional_PerfilConcurso = new HashSet<perfilProfesional_PerfilConcurso>();
        }
    
        public int idConcurso { get; set; }
        public Nullable<int> idPuesto { get; set; }
        public Nullable<int> idInfoRequisitos { get; set; }
        public Nullable<int> idEstado { get; set; }
        public string codConcurso { get; set; }
        public Nullable<System.DateTime> fechaInicio { get; set; }
        public Nullable<System.DateTime> fechaCierre { get; set; }
        public string descripcionConcurso { get; set; }
        public string usuarioCrea { get; set; }
        public Nullable<System.DateTime> fechaCreacion { get; set; }
        public string usuarioModifica { get; set; }
        public Nullable<System.DateTime> fechaModifica { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<aplicaciones> aplicaciones { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual InfoPuesto InfoPuesto { get; set; }
        public virtual InfoRequisitos InfoRequisitos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<perfilProfesional_PerfilConcurso> perfilProfesional_PerfilConcurso { get; set; }
    }
}
